export const CADRES = [
  "accountant",
  "administrative officer",
  "aerodrome engineer",
  "agricultural officer",
  "agricultural research officer",
  "agricutural engineer",
  "animal husbandry officer",
  "architect",
  "archivist",
  "auditor",
  "building officer",
  "chemical engineer",
  "civil and water engineer",
  "civil engineer",
  "clinical psychologist",
  "commercial officer",
  "community development officer",
  "computer engineer",
  "consultant (orthopaedic)",
  "consultant special grade",
  "consultant special grade ii (physician)",
  "cultural officer",
  "dental officer",
  "education officer",
  "electrical engineer",
  "engineer (elect/elect)",
  "environmental health officer",
  "environmental management officer",
  "fisheries",
  "foreign affairs officer",
  "forestry officer",
  "geologist",
  "health education officer",
  "hydrologist",
  "hydrology/hydrogeologist",
  "industrial inspector",
  "industrial officer",
  "information officer",
  "inspector of factories",
  "insurance inspector",
  "labour officer",
  "land officer",
  "land resources officer",
  "legal metrology",
  "librarian",
  "marine officer",
  "mechanical engineer",
  "med. officer (consultant family)",
  "medical consultant radiology",
  "medical imaging scientist",
  "medical lab. scientist",
  "medical officer",
  "meteorologist",
  "mines inspector",
  "nurse tutor",
  "nursing officer",
  "nutrition officer",
  "optometrist",
  "pathologist consultant",
  "petroleum engineer",
  "pharmacist",
  "physiotherapist",
  "planning officer",
  "population programe officer",
  "procurement officer",
  "produce officer",
  "prog. analyst",
  "psychiatrist (consultant)",
  "quantity surveyor",
  "registrar (trade marks)",
  "registrar of co-operative societies",
  "scientific officer (fed. min. of agriculture & food security)",
  "scientific officer (fed. min. of environment)",
  "scientific officer (fed. min. of innovation, science & technology)",
  "scientific officer (fed. min. of regional development)",
  "scientific officer (health & social welfare)",
  "scientific officer (min. of defence)",
  "scientific officer (min. of solid minerals)",
  "scientific officer (min. of steel development)",
  "scientific officer (min. of water resources)",
  "skills dev. and certification officer",
  "social welfare officer",
  "sports officer",
  "state counsel",
  "statistician",
  "structural engineer",
  "surveyor",
  "tourism officer",
  "town planning",
  "veterinary officer",
  "water engineer",
  "youth development officer",
];

export const MDAS = [
  "FED. MIN. OF INFORMATION & NATIONAL ORIENTATION",
  "FED. MIN. OF LABOUR & EMPLOYMENT",
  "FED. MIN. OF LIVESTOCK DEVELOPMENT",
  "FED. MIN. OF YOUTH DEVELOPMENT",
  "OFFICE OF THE ACCOUNTANT GENERAL OF THE FEDERATION",
  "FED. MIN. OF EDUCATION",
  "OFFICE OF THE HEAD OF THE CIVIL SERVICE OF THE FEDERATION",
  "FED. MIN.  OF ENVIRONMENT",
  "NATIONAL SPORTS COMMISSION",
  "FED. MIN. OF HUMANITARIAN AFFAIRS & POVERTY ALLEVIATION ",
  "FED. MIN. OF ARTS, CULTURE & CREATIVE ECONOMY",
  "FED. MIN. OF FINANCE",
  "FED. MIN. OF POWER",
  "FED. MIN. OF INNOVATION, SCIENCE & TECHNOLOGY",
  "OFFICE OF THE SURVEYOR GENERAL OF THE FEDERATION",
  "MIN. OF REGIONAL DEVELOPMENT",
  "FED. MIN. OF INDUSTRY, TRADE & INVESTMENT",
  "OFFICE OF THE AUDITOR GENERAL FOR THE FEDERATION",
  "FED. MIN. OF WOMEN AFFAIRS",
  "MIN. OF DEFENCE",
  "MIN. OF SOLID MINIRALS DEVELOPMENT",
  "FED. MIN. OF COMMUNICATIONS, INNOVATION & DIGITAL ECONOMY",
  "FED. MIN. OF TRANSPORTATION",
  "MIN. OF STEEL DEVELOPMENT",
  "FED. MIN. OF HOUSING & URBAN DEVELOPMENT",
  "MIN. OF POLICE AFFAIRS",
  "FED. MIN. OF JUSTICE",
  "MIN. OF PETROLEUM RESOURCES",
  "FED. MIN. OF AVIATION & AEROSPACE DEVELOPMENT",
  "MIN. OF FOREIGN AFFAIRS",
  "FED. MIN. OF WATER RESOURCES & SANITATION",
  "FED. MIN. OF HEALTH & SOCIAL WELFARE",
  "FED. MIN. OF BUDGET & ECONOMIC PLANNING",
  "FED. MIN. OF AGRICULTURE & FOOD SECURITY",
  "FED. MIN. OF MARINE & BLUE ECONOMY",
  "FED. MIN. OF WORKS",
  "STATE HOUSE",
].sort();
